version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-vol:/data/db

  aggregator-service:
    image: bloomstack/aggregator-service:edge
    ports:
      - "7100:7100"
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - aggregator-service-vol:/home/bloomstack/aggregator-service/files

volumes:
  mongo-vol:
  aggregator-service-vol:
