kind: pipeline
name: default

steps:
- name: test-aggregator-service
  group: tests
  image: node:latest
  commands:
  - cd packages/aggregator-service
  - npm install
  - npm run format:check
  - npm run lint
  # Set environment to test
  - export NODE_ENV=test
  - npm run test
  - npm run test:e2e

- name: test-aggregator-console
  group: tests
  image: registry.gitlab.com/castlecraft/docker-craft/node-latest-headless-chrome:latest
  commands:
  - cd packages/aggregator-console
  - npm install
  - npm run format:check
  - npm run lint
  # Set environment to test
  - export NODE_ENV=test
  - npm run test:server
  - npm run test:e2e
  # For headless chrome
  - export DISPLAY=:99
  - Xvfb :0 -ac -screen 0 1024x768x24 &
  # Test frontend
  - npm run test:client --watch=false
  - npm run e2e

- name: build-staging-aggregator-service
  image: plugins/docker
  # volumes: # Use for local testing
  #   - name: docker
  #     path: /var/run/docker.sock
  settings:
    repo: bloomstack/aggregator-service
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: packages/aggregator-service/Dockerfile
    context: packages/aggregator-service
    tags:
      - edge
  when:
    event:
      - push
    branch:
      - staging

- name: build-staging-aggregator-console
  image: plugins/docker
  settings:
    repo: bloomstack/aggregator-console
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: packages/aggregator-console/Dockerfile
    context: packages/aggregator-console
    tags:
      - edge
  when:
    event:
      - push
    branch:
      - staging

- name: build-production-aggregator-service
  image: plugins/docker
  settings:
    auto_tag: true
    repo: bloomstack/aggregator-service
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: packages/aggregator-service/Dockerfile
    context: packages/aggregator-service
  when:
    event:
      - push
    branch:
      - master

- name: build-production-aggregator-console
  image: plugins/docker
  settings:
    auto_tag: true
    repo: bloomstack/aggregator-console
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: packages/aggregator-console/Dockerfile
    context: packages/aggregator-console
  when:
    event:
      - push
    branch:
      - master

- name: build-docs
  group: docs
  image: node:latest
  commands:
  - npm install gitbook-cli lerna -g
  - npm install
  - lerna clean -y
  - lerna bootstrap
  - rm -fr public
  - gitbook build docs public
  - npm run docs
  when:
    branch:
      - develop
    event:
      exclude:
        - pull_request

- name: publish-docs
  group: docs
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_token
    pages_directory: public
  when:
    branch:
      - develop
    event:
      exclude:
        - pull_request

- name: helm-deploy-staging
  group: deploy
  image: dtzar/helm-kubectl:latest
  environment:
    KUBECONFIG: /etc/deploy/config
    KUBE_CONFIG:
      from_secret: staging_kube_config
  commands:
    - mkdir -p /etc/deploy
    - echo $${KUBE_CONFIG} | base64 -d > $${KUBECONFIG}
    - kubectl config use-context staging
    - helm init --service-account staging-user --client-only
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com/
    - helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
    - helm repo update
    - ./scripts/deploy-staging.sh
  when:
    branch:
      - staging
    event:
      - push

######################################
# Use for local testing docker build #
######################################
# volumes:
# - name: docker
#   host:
#     path: /var/run/docker.sock
