apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
stringData:
  aggregatorServiceMongodbPassword: {{ index .Values "aggregator-service" "mongodbPassword" }}
  aggregatorConsoleMongodbPassword: {{ index .Values "aggregator-console" "mongodbPassword" }}
  vendorKey: {{ index .Values "aggregator-service" "vendorKey" }}
