apiVersion: v1
kind: Namespace
metadata:
  name: bloomtrace-api

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bloomtrace-api-user
  namespace: bloomtrace-api

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bloomtrace-api-user-full-access
  namespace: bloomtrace-api
rules:
- apiGroups: ["", "extensions", "apps", "networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bloomtrace-api-user-view
  namespace: bloomtrace-api
subjects:
- kind: ServiceAccount
  name: bloomtrace-api-user
  namespace: bloomtrace-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bloomtrace-api-user-full-access
